### ISSUE TITLE
*nix support

### ISSUE THREAD

**Issue by MirandaStreeter** [branpk/wafel#6]
```
import os
```

That's a start, right? ;)

**Comment by branpk** [comment]
Theoretically this mainly just comes down to me compiling the sm64 native code for linux/mac and then testing. Most of the wafel code should "just work". 64 bit builds worked at some point so hopefully they still do.

**Comment by MirandaStreeter** [comment]
Ah, sorry, I just assumed based on the readme.

```
   Compiling wafel_core v0.1.0 (/home/miranda/Git/wafel/wafel_core)
error[E0433]: failed to resolve: could not find `um` in `winapi`
  --> src/dll/memory.rs:34:13
   |   
34 | use winapi::um::{dbghelp::SymCleanup, processthreadsapi::GetCurrentProcess};
   |             ^^ could not find `um` in `winapi`

error[E0425]: cannot find function, tuple struct or tuple variant `SymCleanup` in this scope
   --> src/dll/memory.rs:185:17
    |   
185 |                 SymCleanup(GetCurrentProcess());
    |                 ^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `GetCurrentProcess` in this scope
   --> src/dll/memory.rs:185:28
    |   
185 |                 SymCleanup(GetCurrentProcess());
    |                            ^^^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0425, E0433.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `wafel_core`

To learn more, run the command again with --verbose.
Traceback (most recent call last):
  File "/home/miranda/Git/wafel/./build.py", line 24, in <module>
    subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 524, in run 
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cargo', 'build', '--release', '--manifest-path', 'wafel_core/Cargo.toml']' returned non-zero exit status 101.
```
I have not yet looked into what crate/type it's hitting, or if it needs a target type set in Cargo or something simple like that. Partly because I'm busy dealing with broken code at work, partly because I am no rust expert. But if you want more traceback let me know.

Oh, and I learned you need rust nightly the hard way. Just a heads up.

**Comment by branpk** [comment]
Oh sorry I should have been more clear. Next step is for me to build some sm64 source code, which isn't public so I have to do it. That specific error you hit is a bit of windows specific code that will just be removed for other OSes.

**Comment by MirandaStreeter** [comment]
Ah, that wasn't a rhetorical "me". Sorry about that.

And yeah, I figured `winapi` is referring to, uh, `winapi`. :P

**Comment by jgcodes2020** [comment]
has this been worked on?

**Comment by branpk** [comment]
I've successfully built libsm64 on macOS, and in theory linux should work too. The remaining Wafel work is mostly setting up CI, removing a small number of OS-specific things (e.g. Wafel uses tkinter just for file opening/saving, which isn't available on macOS), and then testing. I'm guessing wgpu will be the main source of platform specific bugs.

**Comment by jgcodes2020** [comment]
> I've successfully built libsm64 on macOS, and in theory linux should work too. The remaining Wafel work is mostly setting up CI, removing a small number of OS-specific things (e.g. Wafel uses tkinter just for file opening/saving, which isn't available on macOS), and then testing. I'm guessing wgpu will be the main source of platform specific bugs.

I did some digging for a couple of things.

- On Mac you have to install Tcl/Tk separately using homebrew or the like.
- The Windows bug dealing with dlopen could be replaced with a macro. The macro should expand to the existing code on Windows and nothing on other platforms.

I could definitely consider helping out, but I'd need to learn Rust first.
